# DNS防泄露版本
# 不是必须请勿用，不懂不要随便更改DNS模块
# 必读！！！
# 注意规则在满足自己需求情况下，尽量做到精简，不要过度复杂，以免影响性能。
# 跑裸核用户请自行去掉下方控制面板模块的注释。

# 机场订阅
proxy-providers:
  Airport1:
    url: "机场订阅填到这里，两端引号不要去掉，不要填写到下方链接里去！！"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 直连

# 节点信息
proxies:
  - {name: 直连, type: direct}

# 全局配置 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: warning
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

#external-controller: 0.0.0.0:9090
#secret: ""
#external-ui: "/etc/mihomo/ui"
#external-ui-name: zashboard
#external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# 嗅探
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "+.baidu.com"

# 入站  
tun:
  enable: true
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false

# DNS模块
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter-mode: blacklist
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
  direct-nameserver:
    - 223.6.6.6
    - 223.5.5.5
  nameserver:
    - https://8.8.8.8/dns-query#🚀 默认代理
  nameserver-policy:
    "rule-set:geosite-cn,geosite-mycn,private_domain":
      - 223.6.6.6
      - https://dns.alidns.com/dns-query
  fake-ip-filter:
    - "rule-set:geosite-fakeipfilter"
    - "*.lan"
    - "*.local"
    - "localhost"

# 出站策略
proxy-groups:
  - {name: 🚀 默认代理, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, ♻️ 自动选择]}
  - {name: 🧠 AI, type: select, proxies: [🇺🇲 美国手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动]}
  - {name: 📹 YouTube, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, 直连]}
  - {name: 🍀 Google, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, 直连]}
  - {name: 👨‍💻 Github, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, 直连]}
  - {name: 📲 Telegram, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, 直连]}
  - {name: 🎵 TikTok, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, 直连]}
  - {name: 🎥 Netflix, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, 直连]}
  - {name: 💶 PayPal, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, 直连]}
  - {name: 🎮 Steam, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, 直连]}
  - {name: 🪟 Microsoft, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, 直连]}
  - {name: 🐬 OneDrive, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, 直连]}
  - {name: 🍏 Apple, type: select, proxies: [🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🐸 手动选择, 直连]}
  - {name: 🐠 漏网之鱼, type: select, proxies: [🚀 默认代理, 直连, 🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动]}
  - {name: 📥 Download, type: select, proxies: [直连, 🐸 手动选择, ♻️ 自动选择, 🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动]}
  - {name: 💰 Bybit, type: select, proxies: [🚀 默认代理, 直连, 🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动]}
  - {name: 🔞 KRAV, type: select, proxies: [🚀 默认代理, 直连, 🇺🇲 美国手动, 🇭🇰 香港手动, 🇹🇼 台湾手动, 🇯🇵 日本手动, 🇸🇬 狮城手动]}
  - {name: 🌎 Wechat, type: select, proxies: [直连, 🚀 默认代理]}
  - {name: 🇺🇲 美国手动, type: select, include-all: true, filter: "(?i)美|us|unitedstates|united states"}
  - {name: 🇭🇰 香港手动, type: select, include-all: true, filter: "(?i)港|hk|hongkong|hong kong"}
  - {name: 🇹🇼 台湾手动, type: select, include-all: true, filter: "(?i)台|tw|taiwan"}
  - {name: 🇯🇵 日本手动, type: select, include-all: true, filter: "(?i)日|jp|japan"}
  - {name: 🇸🇬 狮城手动, type: select, include-all: true, filter: "(?i)新加坡|坡|狮城|SG|Singapore"}
  - {name: 🐸 手动选择, type: select, include-all: true}
  - {name: ♻️ 自动选择, type: url-test, include-all: true, tolerance: 20, interval: 300}
  - {name: 🍃 延迟辅助, type: url-test, proxies: [🚀 默认代理, 直连], tolerance: 20, interval: 300}

# 规则匹配
rules:
  - RULE-SET,private_ip,直连,no-resolve
  - RULE-SET,private_domain,直连
  - RULE-SET,geosite-ai,🧠 AI
  - RULE-SET,geosite-youtube,📹 YouTube
  - RULE-SET,geosite-google,🍀 Google
  - RULE-SET,geosite-github,👨‍💻 Github
  - RULE-SET,geosite-onedrive,🐬 OneDrive
  - RULE-SET,geosite-microsoft,🪟 Microsoft
  - RULE-SET,geosite-apple,🍏 Apple
  - RULE-SET,geosite-telegram,📲 Telegram
  - RULE-SET,geosite-tiktok,🎵 TikTok
  - RULE-SET,geosite-netflix,🎥 Netflix
  - RULE-SET,geosite-paypal,💶 PayPal
  - RULE-SET,geosite-steamcn,直连
  - RULE-SET,geosite-steam,🎮 Steam
  - RULE-SET,geosite-download,📥 Download
  - RULE-SET,geosite-bybit,💰 Bybit
  - RULE-SET,geosite-kr,🔞 KRAV
  - RULE-SET,geosite-wechat,🌎 Wechat
  - RULE-SET,geosite-mycn,直连
  - RULE-SET,geosite-!cn,🚀 默认代理
  - RULE-SET,geosite-cn,直连
  - RULE-SET,geoip-google,🍀 Google,no-resolve
  - RULE-SET,geoip-apple,🍏 Apple,no-resolve
  - RULE-SET,geoip-telegram,📲 Telegram,no-resolve
  - RULE-SET,geoip-netflix,🎥 Netflix,no-resolve
  - RULE-SET,geoip-cn,直连,no-resolve
  - MATCH,🐠 漏网之鱼

# 规则集
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}

rule-providers:
  private_domain: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs" }
  geosite-fakeipfilter: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/qwb332/singboxrule/refs/heads/main/config/mihomo/rules/fakeipfilter.mrs" }
  geosite-ai: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  geosite-youtube: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs" }
  geosite-google: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs" }
  geosite-github: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs" }
  geosite-onedrive: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs" }
  geosite-microsoft: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs" }
  geosite-apple: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs" }
  geosite-telegram: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs" }
  geosite-tiktok: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs" }
  geosite-netflix: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs" }
  geosite-paypal: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs" }
  geosite-steamcn: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam@cn.mrs" }
  geosite-steam: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs" }
  geosite-!cn: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs" }
  geosite-cn: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs" }
  geosite-bybit: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bybit.mrs" }

  # 本地转换生成的规则集 (wechat为classical yaml)
  geosite-mycn: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/qwb332/singboxrule/refs/heads/main/config/mihomo/rules/cn.mrs" }
  geosite-download: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/qwb332/singboxrule/refs/heads/main/config/mihomo/rules/download.mrs" }
  geosite-kr: { <<: *domain, url: "https://githubproxy.cc/https://raw.githubusercontent.com/qwb332/singboxrule/refs/heads/main/config/mihomo/rules/kr.mrs" }
  geosite-wechat: { type: http, interval: 86400, behavior: classical, format: yaml, url: "https://githubproxy.cc/https://raw.githubusercontent.com/qwb332/singboxrule/refs/heads/main/config/mihomo/rules/wechat.yaml" }

  # IP 规则集
  private_ip: { <<: *ip, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs" }
  geoip-google: { <<: *ip, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs" }
  geoip-apple: { <<: *ip, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta-lite/geo/geoip/apple.mrs" }
  geoip-telegram: { <<: *ip, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs" }
  geoip-netflix: { <<: *ip, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs" }
  geoip-cn: { <<: *ip, url: "https://githubproxy.cc/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs" }
