payload:
  - '+.o4504926511693824.ingest.sentry.io'
  - '+.mediafire.com'
  - '+.mypikpak.com'
  - '+.mypikpak.net'
  - '+.pickpackapp.com'
  - '+.pikpak.io'
  - '+.pikpak.me'
  - '+.pikpakdrive.com'
